version: "3.9"
services:
    web:
        build:
            context: .
            dockerfile: scripts/Dockerfile
        ports:
            - "5000:5000"
        environment:
            FLASK_APP: "run.py"
            FLASK_ENV: "production"
            MONGODB_HOST: "mongo"
            JWT_SECRET_KEY: "prod_jwt_secret_key"
            JWT_ACCESS_TOKEN_EXPIRES: "3600"
        depends_on:
            - mongo
    mongo:
        image: mongo:4.4
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "example"
            MONGO_INITDB_DATABASE: "app_db"
        ports:
            - "27017:27017"